### ISSUE TITLE
LabProtocol profile works only against LabProtocol DRAFT v0.5 not v0.8

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/isa-ro-crate-profile#12]
Okay (newest version in subfolder): 
https://github.com/BioSchemas/specifications/blob/master/LabProtocol/jsonld/type/LabProtocol_v0.5-DRAFT.jsonld

Not Okay (newest version overall):
https://github.com/BioSchemas/specifications/blob/master/LabProtocol/jsonld/LabProtocol_v0.8-DRAFT.json

What's the truth here and why are these two types so drastically different?

**Comment by floWetzels** [comment]
I don't know what you mean. The first one is the type specification, the other one the bioschemas profile. Our profile only has to be coherent with the type, so we're fine.
