### ISSUE TITLE
What does `sameAs` point to in `LabProtocol`? 

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/isa-ro-crate-profile#13]
`Uri` propery of ISA protocol is already covered by `url` field from schema.org thing

**Comment by floWetzels** [comment]
I'm not sure about this and can't remember why we added both. Could be that one is meant to point to a file within an ARC that describes the protocol whereas the other points to a true external resource like a website? Do you remember, @stuzart? Is it even a realistic scenario that both exist?

**Comment by floWetzels** [comment]
So are you saying that `sameAs` is necessary and something else than `url`? Because your description "an actual file documenting the protocol" basically matches what the description of `url` in the profile says. I'm a bit confused.
@stuzart

**Comment by stuzart** [comment]
The problem with `url` is that in an RO-Crate if you are including an actual file, it needs to referenced as a File (an alias for MediaObject) which wouldn't be compatible with `url`, but would be with `hasPart`. `url` could be used if pointing to something elsewhere, e.g. protocols.io but not if you just want to include a doc or pdf file.

It may even be clearer if we just remove `url` and use `hasPart` for both cases. The RO-Crate docs describe using `File` for both files or web based entities https://www.researchobject.org/ro-crate/1.1/data-entities.html

**Comment by stuzart** [comment]
Actually I've looked into it a bit more and yes, your're right, we just need `url` . If it is a file, we just need to give the filename as the `@id` , and use a `@type` of both `File` and `Labprotocol` e.g
```
{
      "@id": "my-lovely-protocol.pdf",
      "@type": [
        "File",
        "LabProtocol"
      ],
      ....
}
'''
and then reference `my-lovely-protocol.pdf` from the root entity with `hasPart`.

So from the profile we can drop `@sameAs` and don't anything to replace it.

Sorry, I keep forgetting this ro-crate convension of using the `@id` as the file reference rather than a more explicit property.

**Comment by HLWeil** [comment]
So we would have 2 distinct to reference a digital protocol resource:
- If it is a file in the `RO-Crate`/`ARC`, we use `@id`
- If it is a external web resource, we use `uri`

Or did I get this wrong?

**Comment by stuzart** [comment]
it's a bit confusing and I'm trying to get to clarification. The spec itself is known to be confusing, and is trying to be improved to ro-crate 1.2. But the gist of it is that:

- if its a file then in the ro-crate the `@id` should be the path to the file, relative to the root
- if its an extenal web resource, then the `@id` should be the URL
- if its mixed, both a file and available online then `@id` should be the file, and `url` a download link (in 1.2 changing to `contentUrl` for the download link)

in all cases there must be a `hasPart` referencing the `File` as root entities.

In our case, where it is an external web resource, I don't see any harm in also include `url` to point to it, which I think would make it fit with the bioschema profile and I'd imagine make it easier for parsers.

**Comment by stuzart** [comment]
My suggestion is that we include `url` but make it none mandatory, but recommended for an external web source. At the same time, the bioschema for [LabProtocol ](https://bioschemas.org/profiles/LabProtocol/0.8-DRAFT) should replace `sameAs` with `url`, (which is where it originally came from). 

So in the ro-crate, for a file it would appear as:

```
{
      "@id": "my-lovely-protocol.pdf",
      "@type": [
        "File",
        "LabProtocol"
      ],
      ....
}
```

external web resource:

```
{
      "@id": "https://somewhere.com/my-lovely-protocol.pdf",
      "@type": [
        "File",
        "LabProtocol"
      ],
      url: "https://somewhere.com/my-lovely-protocol.pdf"
      ....
}
```

and if mixed, then

```
{
      "@id": "my-lovely-protocol.pdf",
      "@type": [
        "File",
        "LabProtocol"
      ],
      url: "https://somewhere.com/my-lovely-protocol.pdf"
      ....
}
```

The root ro-crate `DataSet` would include the following, but this isn't necessarily part of the Profile, but just part of the ro-crate spec:

```
"hasPart": [
        {
          "@id": "my-lovely-protocol.pdf"
        }
      ]
```
