### ISSUE TITLE
Set family name from MUST to SHOULD

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/isa-ro-crate-profile#15]
https://www.quora.com/What-cultures-do-not-use-family-names#:~:text=As%20well%20as%20the%20mentioned,Sometimes%20they%20invent%20a%20surname.

Some bigger culture groups like javanese people from indonesia don't have surnames, so we should not set this field to MUST. 

Either use MAY or SHOULD instead.

**Comment by floWetzels** [comment]
Sounds reasonable. But how about the first name? Should there be any MUSTs in the person profile other than the ID?

**Comment by HLWeil** [comment]
Hmm, good question. Probably also cases where an ORCID does suffice. So yeah maybe set it to SHOULD.

**Comment by stuzart** [comment]
I completely agree about the cultural differences, and shouldn't be a MUST. 
Could just replace both with `name` instead, this is what the draft bioschemas profile recommends: https://bioschemas.org/profiles/Person/0.3-DRAFT

**Comment by floWetzels** [comment]
Good catch! So should we say `name` is a MUST, but `familyName` and `givenName` are COULD? Or drop them completely?

**Comment by stuzart** [comment]
I would say keep `name` as MUST and drop `familyName` and `givenName`

**Comment by floWetzels** [comment]
Ok, do you agree, @HLWeil @Freymaurer ?

**Comment by HLWeil** [comment]
I agree that this would be the most practictal solution with no further constraints. But as we want to depict the `ISA` model with this profile, I think we should stick to `GivenName + FamilyName`.

**Comment by stuzart** [comment]
sounds good to me, as you say we're constrained by the ISA model.

**Comment by floWetzels** [comment]
Fixed by PR https://github.com/nfdi4plants/isa-ro-crate-profile/pull/19
