### ISSUE TITLE
Integration of Data Fragment Selectors

### ISSUE THREAD

**Issue by floWetzels** [nfdi4plants/isa-ro-crate-profile#21]
Data Fragment Selectors for data outputs of processes can be represented in the RO-Crate by adding the data format and data selector format information to the json object representing the output.

The output is a [schema.org/MediaObject](https://schema.org/MediaObject), with its `@id` being the URL of a file or a directory containing the data selector. Information on how to interpret the data selector (given in the `DataSelectorFormat` column as a URL) is added through the [`usageInfo`](https://schema.org/usageInfo) property. Information on the data format (given in the `DataFormat` column as a URL) is added through the [`encodingFormat`](https://schema.org/encodingFormat) property.

### Example

For example, consider the following process table:

| Input [Sample Name] | Output [Data]          | Data Format | Data Selector Format | 
|-------------|---------------------------------|----------------------------------|--|
| input1       | result.csv#col=1 | text/csv | https://datatracker.ietf.org/doc/html/rfc7111 |
| input2       | result.csv#col=2 | text/csv | https://datatracker.ietf.org/doc/html/rfc7111 |

The corresponding jsonld objects should look like this:

```
{
  "@id": "#some_process_id",
  "@type": "LabProcess",
  "object": ["#Sample_input1","#Sample_input2"],
  "result": ["result.csv#col=1","result.csv#col=2"]
},
{
  "@id": "#result.csv#col=1",
  "@type": "MediaObject",
  "encodingFormat": "text/csv",
  "usageInfo": "https://datatracker.ietf.org/doc/html/rfc711"
},
{
  "@id": "#result.csv#col=2",
  "@type": "MediaObject",
  "encodingFormat": "text/csv",
  "usageInfo": "https://datatracker.ietf.org/doc/html/rfc711"
},
{
  "@id": "#Sample_input1",
  "@type": "Sample"
},
{
  "@id": "#Sample_input2",
  "@type": "Sample"
}
```

**Comment by HLWeil** [comment]
- https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#inputs-and-outputs
- https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#datamap-file

@floWetzels

**Comment by HLWeil** [comment]
I think this is ready to be incorporated? @floWetzels

**Comment by HLWeil** [comment]
Actually, maybe we could model this more closely to Web Annotation Model:
https://www.w3.org/TR/annotation-model/#selectors

**Comment by HLWeil** [comment]
Something like:

```json
{
  "@id": "#result.csv#col=2",
  "@type": {"MediaObject","Annotation"}
  "encodingFormat": "text/csv",
  "body": {
    "source" : "result.csv",
    "selector" : {
       "type" : "FragmentSelector",
       "conformsTo" : "https://datatracker.ietf.org/doc/html/rfc711",
       "value" : "col=2"
    }    
  }
}
```

**Comment by floWetzels** [comment]
Integrated the initial version (without the json model from Web Annotation Model) in PR https://github.com/nfdi4plants/isa-ro-crate-profile/pull/28
