### ISSUE TITLE
No DefinedTerm Profile Defined

### ISSUE THREAD

**Issue by floWetzels** [nfdi4plants/isa-ro-crate-profile#24]
Our ISA-RO-Crate profile doesn't contain any specification/profile regarding the type `DefinedTerm`, although it is an essential part at the core of the ISA model and many properties require it in their type range. Is this an oversight or was it intentional? After all, we do not require any specific restrictions, but it seems weird to me nonetheless.

@HLWeil @stuzart

**Comment by HLWeil** [comment]
I guess it's an oversight based on the type already fitting the OntologyAnnotation from isa-json pretty well. Nonetheless it should be added to the profile for clarity.

**Comment by floWetzels** [comment]
Fixed by PR https://github.com/nfdi4plants/isa-ro-crate-profile/pull/35
