### ISSUE TITLE
DateModified

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/isa-ro-crate-profile#4]
`DateModified` is a field used in `Study` and `Investigation` profiles, but they don't have an corresponding field in ISA(json). Is this by design?

**Comment by floWetzels** [comment]
I adapted the date properties in PR https://github.com/nfdi4plants/isa-ro-crate-profile/pull/17. Should we consider this issue fixed or do we need further modifications, @HLWeil @stuzart?
