### ISSUE TITLE
Assay profile has fields copied from study and investigation

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/isa-ro-crate-profile#5]
Currently, the `Assay` profile contains fields, which do not have a corresponding field in ISA. These seem to copied from either the `Study` or `Investigation` profile.

These include `headline`, `description`, `dateCreated`, `dateModified` and `citation`.

**Comment by floWetzels** [comment]
Fixed by PR https://github.com/nfdi4plants/isa-ro-crate-profile/pull/17
