### ISSUE TITLE
Person ORCID field?

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/isa-ro-crate-profile#8]
Currently we have no field in [Person](https://schema.org/Person) (and [here](https://github.com/nfdi4plants/arc-to-rocrate/blob/main/profiles/investigation.md)) to represent ORCID. 

I suggest using `identifier`, but there might be more appropriate fields.

**Comment by floWetzels** [comment]
I think @HLWeil's suggestion in https://github.com/nfdi4plants/isa-ro-crate-profile/issues/16 could also be applied here.

**Comment by stuzart** [comment]
for the workflow ro crate we use `identifier` for the ORCID, e.g.

```
{
      "@id": "https://orcid.org/0000-0001-8875-7304",
      "@type": "Person",
      "name": "Thomas Roetzer-Pejrimovsky",
      "identifier": "https://orcid.org/0000-0001-8875-7304"
    }
```

**Comment by floWetzels** [comment]
Yes, that's a good option. It fits with Lukas' suggestion on PubMedIDs or DOIs. Since `identifier` allows for `PropertyValue` objects, we can use them to specify that it is an identifier of type ORCID:

```
{
  "@id": "https://orcid.org/0000-0001-8875-7304",
  "@type": "Person",
  "name": "Thomas Roetzer-Pejrimovsky",
  "identifier": {
    "propertyID": "ORCID",
    "value": "0000-0001-8875-7304"
  }
}
```
To me, it doesn't really matter which option w choose.

**Comment by floWetzels** [comment]
Fixed by PR https://github.com/nfdi4plants/isa-ro-crate-profile/pull/19
